language: en
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "SklearnIntentClassifier"
- name: DucklingHTTPExtractor
  url: "http://localhost:8000"
  # dimensions to extract
  dimensions: ["time", "number", "amount-of-money", "distance"]
policies:
- batch_size: 20
  epochs: 600
  max_training_samples: 300
  name: KerasPolicy
- fallback_action_name: action_default_fallback
  name: FallbackPolicy
- max_history: 5
  name: MemoizationPolicy
- name: FormPolicy
- name: MappingPolicy